theme: jekyll-theme-minimal
title: Dide Poyraz
description: MSc Computer Science student at the University of Edinburgh | Distributed Systems · ML · GPU Computing

author:
  name: Dide Poyraz
  email: didepyz@gmail.com
  github: didepoyraz
  linkedin: https://www.linkedin.com/in/dide-poyraz/
  location: Edinburgh, UK


# logo: /assets/profile.png   
show_downloads: false       # set to true for CV or PDF link button

social_links:
  github: https://github.com/didepoyraz
  linkedin: https://www.linkedin.com/in/dide-poyraz/
  email: mailto:didepyz@gmail.com

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
